/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoosample.gui;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author duhi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        pnData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        pnSearch = new javax.swing.JPanel();
        lbSearch = new javax.swing.JLabel();
        cbSearchAttrib = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextArea();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuNewSpecies = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuNewAnimal = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuEditAnimals = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ZOO Sample - Main Form");
        setName("mainFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnData.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnData.setLayout(new java.awt.GridLayout(1, 0));

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tData);

        pnData.add(jScrollPane1);

        getContentPane().add(pnData, java.awt.BorderLayout.CENTER);

        pnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnSearch.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        lbSearch.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbSearch.setText("Search");
        lbSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnSearch.add(lbSearch);

        cbSearchAttrib.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnSearch.add(cbSearchAttrib);

        txtSearch.setColumns(20);
        txtSearch.setRows(5);
        pnSearch.add(txtSearch);

        btnEdit.setText("Edit");
        pnSearch.add(btnEdit);

        btnDelete.setText("Delete");
        pnSearch.add(btnDelete);

        btnSave.setText("Save");
        pnSearch.add(btnSave);

        getContentPane().add(pnSearch, java.awt.BorderLayout.SOUTH);

        menuNewSpecies.setText("File");
        menuNewSpecies.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItem1.setText("New species");
        menuNewSpecies.add(jMenuItem1);

        menuNewAnimal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuNewAnimal.setText("New animal");
        menuNewSpecies.add(menuNewAnimal);
        menuNewSpecies.add(jSeparator1);

        menuExit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuNewSpecies.add(menuExit);

        jMenuBar1.add(menuNewSpecies);

        menuEdit.setText("Edit");
        menuEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        menuEditAnimals.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuEditAnimals.setText("Species");
        menuEdit.add(menuEditAnimals);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuItem6.setText("Animals");
        menuEdit.add(jMenuItem6);

        jMenuBar1.add(menuEdit);

        menuAbout.setText("About");
        menuAbout.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        ActionEvent e = evt;
        if (JOptionPane.showConfirmDialog(this, 
               "Are you sure want to exit?",
               "Close program",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menuExitActionPerformed(new ActionEvent(this, 0, "Exit"));
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbSearchAttrib;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuEditAnimals;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuNewAnimal;
    private javax.swing.JMenu menuNewSpecies;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JTable tData;
    private javax.swing.JTextArea txtSearch;
    // End of variables declaration//GEN-END:variables
}
